// Example Assessment Types based on backend models

export interface QuestionOption {
  id: string; // UUID generated by backend or frontend for new options
  text: string;
  is_correct: boolean;
}

export interface Question {
  id: string;
  assessment: string; // Assessment ID
  order: number;
  question_type: "MC" | "TF" | "SA" | "ES" | "CODE" | "MT" | "FB"; // Match backend choices
  question_type_display: string;
  question_text: string;
  points: number;
  type_specific_data: Record<string, unknown>; // e.g., { options: QuestionOption[], allow_multiple: boolean } for MC
  feedback?: string | null;
  created_at: string;
  updated_at: string;
  // Frontend-only fields
  is_required?: boolean;
  // Frontend-transformed field for MC/TF questions
  options?: Array<{ id: string; option_text: string; is_correct: boolean }>;
}

export interface Assessment {
  id: string;
  course: string; // Course ID
  course_title: string;
  course_slug: string;
  title: string;
  description?: string | null;
  assessment_type: "QUIZ" | "EXAM" | "ASSIGNMENT";
  assessment_type_display: string;
  grading_type: "AUTO" | "MANUAL" | "HYBRID";
  grading_type_display: string;
  due_date?: string | null;
  time_limit_minutes?: number | null;
  max_attempts: number;
  pass_mark_percentage: number;
  show_results_immediately: boolean;
  shuffle_questions: boolean;
  is_published: boolean;
  total_points: number;
  questions: Question[]; // Nested questions for detail view
  created_at: string;
  updated_at: string;
  // User-specific attempt summary fields
  user_attempts_count?: number;
  user_best_score?: number | null;
  user_best_percentage?: number | null;
  user_has_passed?: boolean;
  user_latest_attempt_status?: "IN_PROGRESS" | "SUBMITTED" | "GRADED" | null;
  user_attempts_remaining?: number;
}

export interface AssessmentAttempt {
  id: string;
  assessment: string; // Assessment ID
  assessment_title: string;
  user: { id: string; email: string /* other needed user fields */ }; // Basic user info
  start_time: string;
  end_time?: string | null;
  status: "IN_PROGRESS" | "SUBMITTED" | "GRADED";
  status_display: string;
  answers: Record<string, unknown>; // { question_id: answer_data }
  score?: number | null; // Use number, backend might send string/Decimal
  max_score?: number | null;
  is_passed?: boolean | null;
  graded_by_email?: string | null;
  graded_at?: string | null;
  feedback?: string | null;
  created_at: string;
}
